// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/palemoky/chinese-poetry-api/internal/database"
)

type DynastyStats struct {
	Dynasty *database.Dynasty `json:"dynasty"`
	Count   int               `json:"count"`
}

type Query struct{}

type TypeStats struct {
	Type  *database.PoetryType `json:"type"`
	Count int                  `json:"count"`
}

type SearchType string

const (
	SearchTypeAll     SearchType = "ALL"
	SearchTypeTitle   SearchType = "TITLE"
	SearchTypeContent SearchType = "CONTENT"
	SearchTypeAuthor  SearchType = "AUTHOR"
)

var AllSearchType = []SearchType{
	SearchTypeAll,
	SearchTypeTitle,
	SearchTypeContent,
	SearchTypeAuthor,
}

func (e SearchType) IsValid() bool {
	switch e {
	case SearchTypeAll, SearchTypeTitle, SearchTypeContent, SearchTypeAuthor:
		return true
	}
	return false
}

func (e SearchType) String() string {
	return string(e)
}

func (e *SearchType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchType", str)
	}
	return nil
}

func (e SearchType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
