package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/palemoky/chinese-poetry-api/internal/database"
	"github.com/palemoky/chinese-poetry-api/internal/graph/generated"
	"github.com/palemoky/chinese-poetry-api/internal/graph/model"
)

// Poems is the resolver for the poems field.
//
// 该字段没有自己的 lang 参数，语言变体沿用外层查询的，见 langFromContext。
func (r *authorResolver) Poems(ctx context.Context, obj *database.Author, page *int, pageSize *int) (*database.PoemConnection, error) {
	pag, err := parsePagination(page, pageSize)
	if err != nil {
		return nil, err
	}

	repo := r.repo(ctx, langFromContext(ctx))
	poems, totalCount, err := repo.ListAuthorPoems(obj.ID, pag.PageSize, pag.Offset)
	if err != nil {
		return nil, err
	}

	return buildPoemConnection(poems, pag, totalCount), nil
}

// PoemCount is the resolver for the poemCount field.
//
// 这里以及 Dynasty、PoetryType 上的计数都走默认的简体表：
// 简繁两套表是同一份语料的互转结果，计数完全一致。
func (r *authorResolver) PoemCount(ctx context.Context, obj *database.Author) (int, error) {
	return r.repo(ctx, database.LangHans).CountPoemsByAuthor(obj.ID)
}

// Node is the resolver for the node field.
func (r *authorEdgeResolver) Node(ctx context.Context, obj *database.AuthorEdge) (*database.Author, error) {
	return &obj.Node.Author, nil
}

// PoemCount is the resolver for the poemCount field.
func (r *dynastyResolver) PoemCount(ctx context.Context, obj *database.Dynasty) (int, error) {
	return r.repo(ctx, database.LangHans).CountPoemsByDynasty(obj.ID)
}

// AuthorCount is the resolver for the authorCount field.
func (r *dynastyResolver) AuthorCount(ctx context.Context, obj *database.Dynasty) (int, error) {
	return r.repo(ctx, database.LangHans).CountAuthorsByDynasty(obj.ID)
}

// Content is the resolver for the content field.
func (r *poemResolver) Content(ctx context.Context, obj *database.Poem) ([]string, error) {
	var content []string
	if err := json.Unmarshal(obj.Content, &content); err != nil {
		return nil, err
	}
	return content, nil
}

// PoemCount is the resolver for the poemCount field.
func (r *poetryTypeResolver) PoemCount(ctx context.Context, obj *database.PoetryType) (int, error) {
	return r.repo(ctx, database.LangHans).CountPoemsByType(obj.ID)
}

// Poem is the resolver for the poem field.
func (r *queryResolver) Poem(ctx context.Context, id string, lang *database.Lang) (*database.Poem, error) {
	repo := r.repo(ctx, parseLang(lang))

	poem, err := repo.GetPoemByID(id)
	if err != nil {
		return nil, err
	}
	return poem, nil
}

// Poems is the resolver for the poems field.
func (r *queryResolver) Poems(ctx context.Context, lang *database.Lang, page *int, pageSize *int, after *string, dynastyID *string, authorID *string, typeID *string) (*database.PoemConnection, error) {
	pag, err := parsePaginationWithCursor(page, pageSize, after)
	if err != nil {
		return nil, err
	}

	// 解析各项过滤 ID
	dynastyIDInt, err := parseOptionalID(dynastyID)
	if err != nil {
		return nil, err
	}
	authorIDInt, err := parseOptionalID(authorID)
	if err != nil {
		return nil, err
	}
	typeIDInt, err := parseOptionalID(typeID)
	if err != nil {
		return nil, err
	}

	// GraphQL schema 只暴露单个 typeID；仓储层接收切片，
	// 是因为 REST 接口允许重复传入 type_id 参数。
	var typeIDs []int64
	if typeIDInt != nil {
		typeIDs = []int64{*typeIDInt}
	}

	// 多取一条用于判断还有没有下一页，由 buildPoemConnection 截掉
	limit := pag.PageSize + 1

	repo := r.repo(ctx, parseLang(lang))
	var poems []database.Poem
	var totalCount int
	if pag.IsCursor() {
		poems, totalCount, err = repo.ListPoemsAfter(limit, pag.After, dynastyIDInt, authorIDInt, typeIDs)
	} else {
		poems, totalCount, err = repo.ListPoemsWithFilter(limit, pag.Offset, dynastyIDInt, authorIDInt, typeIDs)
	}
	if err != nil {
		return nil, err
	}

	return buildPoemConnection(poems, pag, totalCount), nil
}

// SearchPoems is the resolver for the searchPoems field.
func (r *queryResolver) SearchPoems(ctx context.Context, query string, lang *database.Lang, searchType *model.SearchType, page *int, pageSize *int) (*database.PoemConnection, error) {
	// 统一走公共的解析函数，而非直接读取参数——
	// 后者正是本 resolver 曾经绕过 pageSize 上限的原因。
	pag, err := parsePagination(page, pageSize)
	if err != nil {
		return nil, err
	}

	// 把 GraphQL 的搜索类型映射为仓储层的取值
	st := "all"
	if searchType != nil {
		switch *searchType {
		case model.SearchTypeTitle:
			st = "title"
		case model.SearchTypeContent:
			st = "content"
		case model.SearchTypeAuthor:
			st = "author"
		}
	}

	langVal := parseLang(lang)
	repo := r.repo(ctx, langVal)
	poems, total, err := repo.SearchPoems(query, st, pag.Page, pag.PageSize)
	if err != nil {
		return nil, err
	}

	// 用公共函数构造 connection，不再手写。手写版本的游标在每页内都从 0 开始编号，
	// 导致第 2 页首条边的游标与第 1 页的相同；而且没有填 startCursor 与 endCursor，
	// 与其他所有 connection 的行为不一致。
	return buildPoemConnection(poems, pag, int(total)), nil
}

// RandomPoem is the resolver for the randomPoem field.
func (r *queryResolver) RandomPoem(ctx context.Context, lang *database.Lang, dynastyID *string, typeID *string) (*database.Poem, error) {
	// 解析过滤 ID。格式错误的 ID 一律报错，而不是丢弃该过滤条件：
	// 被丢弃的过滤条件会把查询范围扩大到全量语料并返回一首无关的诗，
	// 这与一次正常请求毫无区别。
	dynastyIDInt, err := parseOptionalID(dynastyID)
	if err != nil {
		return nil, err
	}

	typeIDInt, err := parseOptionalID(typeID)
	if err != nil {
		return nil, err
	}
	var typeIDs []int64
	if typeIDInt != nil {
		typeIDs = []int64{*typeIDInt}
	}

	// 与 REST 一致，带语言上下文调用仓储层的 GetRandomPoem
	langVal := parseLang(lang)
	repo := r.repo(ctx, langVal)
	return repo.GetRandomPoem(dynastyIDInt, nil, typeIDs)
}

// Author is the resolver for the author field.
func (r *queryResolver) Author(ctx context.Context, id string, lang *database.Lang) (*database.Author, error) {
	authorID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}

	// 走 Repository 的方法，由它处理动态表名
	return r.repo(ctx, parseLang(lang)).GetAuthorByID(authorID)
}

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context, lang *database.Lang, page *int, pageSize *int, dynastyID *string) (*database.AuthorConnection, error) {
	pag, err := parsePagination(page, pageSize)
	if err != nil {
		return nil, err
	}

	dynastyIDInt, err := parseOptionalID(dynastyID)
	if err != nil {
		return nil, err
	}

	repo := r.repo(ctx, parseLang(lang))
	authors, totalCount, err := repo.ListAuthorsWithFilter(pag.PageSize, pag.Offset, dynastyIDInt)
	if err != nil {
		return nil, err
	}

	return buildAuthorConnection(authors, pag, totalCount), nil
}

// Dynasties is the resolver for the dynasties field.
func (r *queryResolver) Dynasties(ctx context.Context, lang *database.Lang) ([]*database.Dynasty, error) {
	var dynasties []*database.Dynasty
	langVal := parseLang(lang)
	err := r.DB.Table(database.DynastiesTable(langVal)).Order("id").Find(&dynasties).Error
	if err != nil {
		return nil, err
	}
	return dynasties, nil
}

// PoemTypes is the resolver for the poemTypes field.
func (r *queryResolver) PoemTypes(ctx context.Context, lang *database.Lang) ([]*database.PoetryType, error) {
	var types []*database.PoetryType
	langVal := parseLang(lang)
	err := r.DB.Table(database.PoetryTypesTable(langVal)).Order("id").Find(&types).Error
	if err != nil {
		return nil, err
	}
	return types, nil
}

// Statistics is the resolver for the statistics field.
func (r *queryResolver) Statistics(ctx context.Context, lang *database.Lang) (*database.Statistics, error) {
	return r.repo(ctx, database.LangHans).GetStatistics()
}

// PoemsByDynasty is the resolver for the poemsByDynasty field.
func (r *statisticsResolver) PoemsByDynasty(ctx context.Context, obj *database.Statistics) ([]*model.DynastyStats, error) {
	stats := make([]*model.DynastyStats, len(obj.PoemsByDynasty))
	for i, ds := range obj.PoemsByDynasty {
		stats[i] = &model.DynastyStats{
			Dynasty: &ds.Dynasty,
			Count:   ds.PoemCount,
		}
	}
	return stats, nil
}

// PoemsByType is the resolver for the poemsByType field.
func (r *statisticsResolver) PoemsByType(ctx context.Context, obj *database.Statistics) ([]*model.TypeStats, error) {
	stats := make([]*model.TypeStats, len(obj.PoemsByType))
	for i, ts := range obj.PoemsByType {
		stats[i] = &model.TypeStats{
			Type:  &ts.PoetryType,
			Count: ts.PoemCount,
		}
	}
	return stats, nil
}

// Author returns generated.AuthorResolver implementation.
func (r *Resolver) Author() generated.AuthorResolver { return &authorResolver{r} }

// AuthorEdge returns generated.AuthorEdgeResolver implementation.
func (r *Resolver) AuthorEdge() generated.AuthorEdgeResolver { return &authorEdgeResolver{r} }

// Dynasty returns generated.DynastyResolver implementation.
func (r *Resolver) Dynasty() generated.DynastyResolver { return &dynastyResolver{r} }

// Poem returns generated.PoemResolver implementation.
func (r *Resolver) Poem() generated.PoemResolver { return &poemResolver{r} }

// PoetryType returns generated.PoetryTypeResolver implementation.
func (r *Resolver) PoetryType() generated.PoetryTypeResolver { return &poetryTypeResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Statistics returns generated.StatisticsResolver implementation.
func (r *Resolver) Statistics() generated.StatisticsResolver { return &statisticsResolver{r} }

type (
	authorResolver     struct{ *Resolver }
	authorEdgeResolver struct{ *Resolver }
	dynastyResolver    struct{ *Resolver }
	poemResolver       struct{ *Resolver }
	poetryTypeResolver struct{ *Resolver }
	queryResolver      struct{ *Resolver }
	statisticsResolver struct{ *Resolver }
)
